extra_suffix = "planet_game"
production = "yes"
# dev_build = "yes"
# debug_symbols = "yes"
# optimize = "none"
precision = "double"
accesskit = "no"
num_jobs = 18

module_camera_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gridmap_enabled = "no"
module_jsonrpc_enabled = "no"
module_ktx_enabled = "no"
module_mbedtls_enabled = "no"
module_mobile_vr_enabled = "no"
module_multiplayer_enabled = "no"
module_openxr_enabled = "no"
module_tga_enabled = "no"
module_upnp_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"

