# Generated using https://godot-build-options-generator.github.io

extra_suffix = "zombie_game"
production = "yes"
# dev_build = "yes"
precision = "double"
use_llvm = "yes"

#jolt_trace_vehicle = "yes"
#jolt_enable_asserts = "yes"
#jolt_enable_asserts_mutex = "no"
#jolt_enable_trace = "yes"

module_camera_enabled = "no"
module_dds_enabled = "no"
module_enet_enabled = "no"
module_gridmap_enabled = "no"
module_jsonrpc_enabled = "no"
module_ktx_enabled = "no"
module_mbedtls_enabled = "no"
module_mobile_vr_enabled = "no"
module_multiplayer_enabled = "no"
module_openxr_enabled = "no"
#module_regex_enabled = "no"
module_tga_enabled = "no"
module_upnp_enabled = "no"
module_webrtc_enabled = "no"
module_websocket_enabled = "no"
module_webxr_enabled = "no"

